[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "aiogram>=3.20.0.post0",
    "f>=0.0.1",
    "flask>=3.1.0",
    "pypydispatch>=1.2.1",
    "tlgbotfwk>=0.4.61",
]
